### ISSUE TITLE
COMBINE_SUPP requires some updates

### ISSUE THREAD

**Issue by Gopi2345** [pharmaverse/metatools#25]
COMBINE_SUPP is not working as expected when combining AE and SUPPAE  or TR and SUPPTR. 
1) In both AE and TR, it is complaining about character vs numeric --SEQ variables. 
2) In TR and SUPPTR it is expecting QEVAL, which is not required in SUPPTR as TREVAL covers the same information.

**Comment by statasaurus** [comment]
I will look into it. Thank you for the report

**Comment by statasaurus** [comment]
Now corrected in main and will be released with the next release

**Comment by Gopi2345** [comment]
Thank you
