### ISSUE TITLE
Duplicate value in create_var_from_codelist documentation

### ISSUE THREAD

**Issue by bms63** [pharmaverse/metatools#26]
Not sure if this is a typo or intentional.

![image](https://user-images.githubusercontent.com/10111024/171215422-f9fb3097-67c2-41d2-a405-110fa2ad2083.png)

**Comment by statasaurus** [comment]
So is male. I was just showing it would work on a dataset going across all rows, even duplicates. But, if the example is confusing I can change it.

**Comment by bms63** [comment]
I'm sorry I completely misunderstood the example.  I thought that was a codelist being created then applied to a dataset.  lol my bad...please disregard.
