### ISSUE TITLE
combine_supp:  Can't join on `x$DSSEQ` x `y$DSSEQ` because of incompatible types.

### ISSUE THREAD

**Issue by bms63** [pharmaverse/metatools#30]
Hey Christina,

I was using `derive_var_suppqual` from admiral previously and this was nice QoL for joining the datasets together, i.e. changing the supp --seq to numeric so I can merge them together.  I think this is the code that was previously used in `derive_var_suppqual `to do this.  Do you have time to make this update?  I can tinker with it if necessary.

![image](https://user-images.githubusercontent.com/10111024/172945364-fbb90421-dc18-4816-84ad-0853f4b475e6.png)

Here is the error I am getting from the funcion.

> combine_supp(ds, suppds)
Error: Can't join on `x$DSSEQ` x `y$DSSEQ` because of incompatible types.
ℹ `x$DSSEQ` is of type <double>>.
ℹ `y$DSSEQ` is of type <character>>.

**Comment by statasaurus** [comment]
This has been fixed in main but there isn't a rerelease to CRAN yet as it is the only issue that has come through. But if you install from main this will work
