### ISSUE TITLE
drop_unspec_vars: note to console idea

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/metatools#38]
@statasaurus idea for `drop_unspec_vars`: would be nice to get a note to console with a list of the variables dropped, so that the user could double check these were true temporary variables no longer needed, rather than things they forgot to spec that they actually did need.

**Comment by statasaurus** [comment]
I love that idea! I will try to add it when I get back from conf.

**Comment by statasaurus** [comment]
This is now on CRAN
