### ISSUE TITLE
create check utils that can help locate the records with issues

### ISSUE THREAD

**Issue by yli110-stat697** [pharmaverse/metatools#42]
Hi,

I'm part of a data curation & integration group within Roche, and we are developing a package for data quality check. For example, we want to identify the records/rows from input dataframe (ADaM dataset) that some variables don't comply with controlled terminology values. It seems that we can make your `metacore` and `metatools` packages as dependency. However the check functions you have seem to only throw a warning and miss the detailed records from the original input. We are proposing some check utils function that can hold the details of the check, and the your check function can wrap around that util function. Take `check_ct_col` as an example, below is our proposal

```
check_ct_col_util <- function(data, metacore, var, na_acceptable = NULL) {
  var <- var
  col_name_str <- as_label(enexpr(var)) %>%
    str_remove_all("\"")
  if (!col_name_str %in% names(data)) {
    stop(paste(col_name_str, "not found in dataset. Please check and try again"))
  }
  ct <- get_control_term(metacore, {{ var }})
  if (is.vector(ct)) {
    check <- ct
  } else if ("code" %in% names(ct)) {
    check <- ct %>% pull(code)
  } else {
    stop("We currently don't have the ability to check against external libraries")
  }
  core <- metacore$ds_vars %>%
    filter(variable == col_name_str) %>%
    pull(core)
  attr(core, "label") <- NULL
  test <- ifelse(is.null(na_acceptable), !identical(core, "Required"), na_acceptable)
  if (test) {
    if (all(is.character(check))) {
      check <- c(check, NA_character_, "")
    } else {
      check <- c(check, NA)
    }
  }
  test <- pull(data, {{ var }}) %in% check
  names(test) <- rownames(data)
  return(test)
}

check_ct_col <- function(data, metacore, var, na_acceptable = NULL) {
  var = enexpr(var)
  test <- check_ct_col_util(data=data, metacore=metacore, var=var, na_acceptable=na_acceptable)
  if(all(test)){
    data
  } else {
    extra <- pull(data, {{ var }})[!test] %>%
      unique() %>%
      paste0("'", ., "'") %>%
      paste0(collapse = ", ")
    stop(paste("The following values should not be present:\n", extra))
  }
}
```

We can help with making such changes if you agree, otherwise we have to copy half of your code and makes changes in our packages, which is not very sustainable in the long run. @aboruvka @adchan11

**Comment by statasaurus** [comment]
Sorry it took so long to respond to this. I tried to run the code and it doesn't work. Are you just asking for row numbers in the error message? It might be easier to actually put a wrapper around `check_ct_col` to capture the error and get the row numbers from that. We can potentially think about adding that

**Comment by adchan11** [comment]
@statasaurus are you able to implement the util function from @yli110-stat697 ?

**Comment by statasaurus** [comment]
I am not going to implement it exactly as you have it, but I will update it. The update should be on CRAN by feb 14th

**Comment by yli110-stat697** [comment]
Thanks @statasaurus ! As along as a function to return the row number will be great!
