### ISSUE TITLE
{metatools} has been archived on CRAN

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [pharmaverse/metatools#47]
```
install.packages("metatools")
```

does not work anymore:

<pre>
Warning in install.packages :
  package ‘metatools’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
</pre>

**Comment by rossfarrugia** [comment]
it's back now: https://cran.r-project.org/web/packages/metatools/index.html, so @statasaurus hope you're ok with me closing this issue.
