### ISSUE TITLE
Function to check / derive the Dataset Maximum Column Length

### ISSUE THREAD

**Issue by cpiraux** [pharmaverse/metatools#53]
I find it would be nice to have a function to derive the length of column.
In the FDA Study Data Technical Conformance Guide (March 2023) we read in section 3.3.3:
![image](https://user-images.githubusercontent.com/69685640/234190262-5b3fe241-bf2e-43d6-8e68-4e1e4b57c1d0.png)

In the process to have the metadata length, when we write the specs before the dataset creation, we only have the length from the MDR. To follow the dataset column length guidance from the FDA, we need a post-processing tool the derive the maximum length of the variable once the dataset is finalized. 
The length from metadata is used by the R package xportr to generate xpt files for submission.
Note: the maximum length in metadata should also take into account codelist values as some of the values may not be present in the data

**Comment by rossfarrugia** [comment]
@statasaurus @bms63 @cpiraux  Do we need this issue any longer now that its been catered for in xportr via https://github.com/atorus-research/xportr/issues/183?

**Comment by bms63** [comment]
I'm happy to have this closed.  I believe @cpiraux raised this issue, but then implemented it in xportr.  Are you happy @cpiraux with xportr?

**Comment by cpiraux** [comment]
I agree to close the issue as it has been implemented in xportr. I raised this issue a long time ago, and I don’t even remember it :sweat_smile:.
