### ISSUE TITLE
Turn off controlled terminology checks for results as character findings

### ISSUE THREAD

**Issue by anajens** [pharmaverse/metatools#57]
It would be helpful if users can configure `check_ct_data()` to exclude certain variables.

For example, variables like `LB.LBSTRESC` have code lists applicable to categorical test results like “ABNORMAL”, “NORMAL”, “POSITIVE”. Users will see an error from `check_ct_data()` for the character findings of a numeric result eg. “20.1” which typically would not be added to the controlled terminology reference in the `metacore` object.

An example using dummy data:
![image](https://github.com/pharmaverse/metatools/assets/43623360/381d5ee3-6962-4f14-a458-daba2fb1bf13)

**Comment by anajens** [comment]
FYI @rossfarrugia @millerg23

**Comment by rossfarrugia** [comment]
@statasaurus would you be interested in accepting contribution PRs here from any of our admiral developers? i think this one could be something we help to enhance and would help user experience. the timing might be better now than when we last discussed when Stefan was going to make some PRs.

**Comment by statasaurus** [comment]
Yes I am happy to accept PRs

**Comment by rossfarrugia** [comment]
thanks - will check options and get back to you

**Comment by statasaurus** [comment]
I do think it should be considered about how this is done. So I would be happy to chat with whoever takes this up about the best way to do this without causing too much confusion in the api
